require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sun' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'sunTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'sun-tvOS' do
  # Pods for sun-tvOS

  target 'sun-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
